#!/bin/bash
# SPDX-FileCopyrightText: 2023 Matt Gleason <mjgleason@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# SPDX-FileCopyrightText: 2021 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Rust format checking credit to @eugene-babichenko on github

# Check lints
echo Running lints...

HAS_ISSUES=0
FIRST_FILE=1

for file in $(git diff --name-only --staged); do
    FMT_RESULT="$(rustfmt --skip-children --force --write-mode diff $file 2>/dev/null || true)"
    if [ "$FMT_RESULT" != "" ]; then
        if [ $FIRST_FILE -eq 0 ]; then
            echo -n ", "
        fi
        echo -n "$file"
        HAS_ISSUES=1
        FIRST_FILE=0
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

echo ". Your code has formatting issues in files listed above. Format your code with \`make format\` or call rustfmt manually."
exit 1

reuse lint
if [ $? -eq 0 ]
then
  echo -e "Lint succeeded."
  exit 0
else
  echo -e "\n=======================================================" >&2
  echo -e "Lint failed.  Fix the issues shown above and try again." >&2
  echo -e "=======================================================\n" >&2
  exit 1
fi
